name: Tvmj
favicon: null
layout_spectrum: 0.697637
typography_spectrum: 0.320623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212322'
    - '#5a5c46'
    - '#928050'
    - '#b4a181'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
