layout_spectrum: 0.697637
typography_spectrum: 0.320623
color:
  saturation: 0.415145
  lightness: 0.6106337
  brandStrength: 0.5418904
  rhythmicContrast: 0.7631579
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Tvmj
